AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Express.js API with DynamoDB

Parameters:
  TableName:
    Type: String
    Default: Employees
    Description: Name of the existing DynamoDB table

Globals:
  Function:
    Timeout: 120
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: production
        DYNAMODB_TABLE_NAME: !Ref TableName
        S3_BUCKET_NAME: !Ref FileStorageBucket

Resources:
  # S3 Bucket
  FileStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-file-storage
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 7 # Auto delete after 7 days

  # DynamoDB Table
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-users
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # Lambda Function
  ExpressApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-api
      CodeUri: ./
      Handler: src/lambda.handler
      Description: Express.js API Lambda Function
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - S3CrudPolicy:
            BucketName: !Ref FileStorageBucket
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Format: esm
        MainFields: module,main
        EntryPoints:
          - src/lambda.js
        External:
          - "@aws-sdk/*"
          - "xlsx"
          - "moment"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/

  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ExpressApiFunction.Arn

  TableName:
    Description: DynamoDB Table Name
    Value: !Ref UsersTable

  BucketName:
    Description: S3 bucket for file storage
    Value: !Ref FileStorageBucket
